extends:
  - ./node_modules/commitlint-config-gitmoji
rules:

  subject-case:
    - 2
    - never
    -
      - sentence-case
      - start-case
      - pascal-case
      - upper-case

  type-case:
    - 2
    - always
    - lower-case

  header-max-length:
    - 2
    - always
    - 76
