---
  env:
    browser: true
    node: true
    es2020: true
  extends:
    - eslint:recommended
    - plugin:md/recommended
    - plugin:node/recommended
    - plugin:yaml/recommended
    - plugin:json/recommended
  plugins:
    - md
    - yaml
    - json
    - node
  rules:
    no-unused-vars: ['warn']
    node/no-unpublished-require: ['off']
  ignorePatterns:
    - node_modules/
    - public/
    - test/
    - ext/
    - \*config.js
    - CHANGELOG.md
    - content/post/*.md
