variables:
  NODE_ENV: $CI_COMMIT_REF_NAME # based on whatever branch

.job_template: &job_default
  image: registry.gitlab.com/hauntgg/dapp/build:rolling
  interruptible: true
  tags:
    - rn-beefer
  before_script:
    - ln -s /cache/node_modules ./node_modules
  script:
    - yarn build
  after_script:
    - mv hugo/public .
  artifacts:
    paths:
      - public/

dev:
  <<: *job_default
  stage: build
  when: manual
  only:
    - dev
    - preview

preview:
  <<: *job_default
  stage: build
  variables:
    NODE_ENV: release
  only:
    - preview
    - v2-dapp
  script:
    - yarn && yarn build
    - rm -rf public/layouts public/data public/assets

pages:
  <<: *job_default
  when: manual
  stage: deploy
  image: registry.gitlab.com/hauntgg/dapp/$RELEASE_IMAGE
  variables:
    # NODE_ENV: $CI_COMMIT_REF_NAME
    GL_TOKEN: $CI_JOB_TOKEN
    RELEASE_IMAGE: build:rolling # enable when gitlab / hugo isnt broken
  only:
    - release
  script:
    - mkdir -p static
    - "[[ $RELEASE_IMAGE = build:rolling ]] && yarn && yarn build || cp -R /public ." # only build:rolling has yarn + deps
    - rm -rf public/layouts public/data public/assets
  # after_script:
  #   - yarn run semantic-release
