version: "3.8"

services:

  build:
    build:
      context: ..
      dockerfile: ./docker/build.Dockerfile
    image: registry.gitlab.com/hauntgg/hauntgg-frontend/build:rolling

  server:
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
      args:
        NODE_ENV: $NODE_ENV
    image: registry.gitlab.com/hauntgg/hauntgg-frontend/server:$NODE_ENV
    ports:
      - 1313:1313/tcp
    environment:
      NODE_ENV: $NODE_ENV
